### ISSUE TITLE
Milestone 3 - Checklist + Lab Feedback

### ISSUE THREAD

**Issue by vtaskaev1** [UBC-MDS/beijing_air_quality_analysis#78]
Main Tasks for Milestone 3:
- [x] Create Makefile
- [x] Address TA feedback of Milestone 1

Lab Feedback - to verify as these are common issues:
- [x] License - check that copyright holders are author names
- [x] Code of conduct - include a contact email
- [x] Figure captions - check all figures have them
- [x] Reports should have abstract or executive 

EDA Plot Summary
- [x] Figure 1 and 2 summary revision
- [x]  Vadim: Makefile description + revising clean_all to clean 
- [x]  Jz: Change the “between… and…” in the main question to “from… to…”
- [x] Jaq: Editing/removing the "reinstated question" part in EDA  (the lines underneath the monthly figure explanation)

- [ ] Macy: Deleting runall.sh

**Comment by Jacq4nn** [comment]
Final edits to be made @zjr-mds @Jacq4nn 

- [x] Edit summary, intro, conclusion (remove all social implications as it does not make sense)
- [x] Edit the results and discussion 
- [ ] edit EDA (too many plots without text separating it)
- [ ] edit html link to new report
